### ISSUE TITLE
FR: language, password change and API fields in custom user view

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1007]
We have to choose between no internal user view (no additional fields) and custom user view without language selection, password change (old, new) and API.
Best would be to add the internal fields in the Edit user custom view but if not possible, at least to choose to add them internally once the custom user view is selected as default.
What do you think @glutamate ?

**Comment by glutamate** [comment]
I started working on this, but then I realised that even if you have chosen a user settings form, use are still sees the language at the top and the password change at the bottom. So maybe I don't understand what do you mean here. Could you outline more clearly how you are expecting it to work?

Here is what I see when I assign a custom user settings view - made it the password fields because that was what I was going to work on. This has my custom form in the middle, language at the top and password at the bottom

![Screenshot 2021-12-08 at 11 23 46](https://user-images.githubusercontent.com/43804/145200353-e6aa9916-1bd4-4b58-b099-a69b362236b1.png)

I think I can add language at least to the fields that you are allowed to change in the user edit views. Are you then expecting the language choice to disappear when a custom user settings view has been assigned?

**Comment by j2l** [comment]
You're totally right @glutamate 
Yesterday, I don't remember how, I got a limited form (custom without language and password). I guess the page was cached and not showing its update or I was seeing the view directly, not the internal menu. Never mind.

About the API token though, would it be possible, as an option, for the user to generate it?
And is there a trigger associated to it?

> Are you then expecting the language choice to disappear when a custom user settings view has been assigned?

Only, when you have custom fields for the user, showing them between email+language and change password is not really great. Would it be possible to move languages and email below the custom fields?
Changing language is very useful (believe it or not, I purposefully changed my main OS and browser language to English (but not on some other software like accounting) while the keyboard remains in French and locales are Canadian (Y-M-D), translated content is not fully working though since some translations are not done for now).

**Comment by glutamate** [comment]
> About the API token though, would it be possible, as an option, for the user to generate it?

You are right, it should be here rather in the admin's user view. will move.

> And is there a trigger associated to it?

No, not right now, but we could add a trigger for API key generated. Is this useful?

> Not really, but when you have custom fields for the user, showing them between email+language and change password is not really great. Would it be possible to move languages and email below the custom fields?

Yes, this is a good idea

> Also, "User Settings" title should be removed because sometimes you have a 1-1 relationship with other fields so they end up in the user table and they are not "settings".

Maybe if there is a custom view, we could make the menu title equal the view name?

**Comment by j2l** [comment]
> No, not right now, but we could add a trigger for API key generated. Is this useful?

Yes, since "user wants to use the API starting now" means you may start monitoring this API token for usage (throttle, pay per API call, ...). I wonder if the stripe pack could manage pay per API call though.

> we could make the menu title equal the view name?

Perfect!

**Comment by j2l** [comment]
Closing this one to lower my open tickets :smile:
