### ISSUE TITLE
Site crashed after installing ssl certificate via certbot

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1370]
1 - I set the **base URL** with the IP of my VPS in this way http://66.xxx.xxx/

2 - After install SSL cert from certbot

3 - after that, the site didn't start anymore

I tried by terminal and I get the following error
![image](https://user-images.githubusercontent.com/50465150/189647879-baa859a4-02ed-4688-80ad-1b0a8c7dda85.png)

I did not change any settings in the .config/.saltcorn file

wouldn't want to lose all the work I've already put into my site

**Comment by gianlucafiore** [comment]
![image](https://user-images.githubusercontent.com/50465150/189649880-3601b247-60b9-4bf4-963c-a3a007b7983a.png)

again, I did not change any settings

**Comment by gianlucafiore** [comment]
I had to reinstall the site respecting the user and the database, for the moment it works

**Comment by gianlucafiore** [comment]
![image](https://user-images.githubusercontent.com/50465150/189655666-01f23ce9-0194-4e8d-a311-6f150ddd8235.png)

this method is not working correctly... at the moment I'm not going to use it

**Comment by glutamate** [comment]
@gianlucafiore your base url should be set to your domain name (http://mydomain.com or https://mydomain.com), not the IP address. I should probably check that this has not been set to the IP address because as you have discovered it is very easy to break things when the SSL install goes wrong.

I don't think it's possible to obtain an SSL certificate for an IP address, but in any case it is not currently supported. There is a discussion here https://stackoverflow.com/questions/2043617/is-it-possible-to-have-ssl-certificate-for-ip-address-not-domain-name, which seems to indicate it is technically possible but rare and not supported by Let'sEncrypt

**Comment by gianlucafiore** [comment]
perfect, thank you very much.. 

and really wonderful tool, every day better!! 🥇

**Comment by gianlucafiore** [comment]
> @gianlucafiore your base url should be set to your domain name (http://mydomain.com or https://mydomain.com), not the IP address. I should probably check that this has not been set to the IP address because as you have discovered it is very easy to break things when the SSL install goes wrong.
> 
> I don't think it's possible to obtain an SSL certificate for an IP address, but in any case it is not currently supported. There is a discussion here https://stackoverflow.com/questions/2043617/is-it-possible-to-have-ssl-certificate-for-ip-address-not-domain-name, which seems to indicate it is technically possible but rare and not supported by Let'sEncrypt

Excellent, working with domain name
