### ISSUE TITLE
table/discover shows history subtables

### ISSUE THREAD

**Issue by pyhedgehog** [saltcorn/saltcorn#1439]
**Describe the bug**
Table discovery shows history subtables.

**To Reproduce**
1. Create table 'test1' with version history.
2. Click on 'Tables'->'Discover tables'
3. See `test1__history`.

**Expected behavior**
Table `test1__history` should be hidden, like all already defined.

**Screenshots**
![image](https://user-images.githubusercontent.com/1286400/197609962-ba799db0-31f7-4735-b0e2-acb8c74de535.png)

**Comment by AleksandrSokolov** [comment]
@pyhedgehog I think this expected behavior because in some cases we need to access table_history data in Saltcorn UI. For example, to show history for users. In some specific cases also can be updated via use interface (for some specific I think it possible). Because Saltocorn uses table_history only for insert history of main table there are minimal direct impact to Saltcorn logic.
But I agreed with you that functionality to import table_history is need only in "expert mode" when user totally understood what he doing. So I purpose add flag "show history tables" in discovery dialog or flag "DISCOVER_TABLE_HISTORY" in Saltcorn configuration.
