### ISSUE TITLE
Get current date/time upon submission

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1588]
I have a form that includes submission date that I would like to, upon submission, automatically fill in the current date and time the form is submitted. Is it possible to do this?

**Comment by gianlucafiore** [comment]
yes, of course, what you should do is have a date field in the table where the data is stored, if you want you can put it as necessary, when you create the editing form you don't include the field  date, or rather you delete it since it is created by default, and when you click next in the form it asks you what default value you want to give it, and you have the option now
