### ISSUE TITLE
Message "The build was successfully" but was not

### ISSUE THREAD

**Issue by jljabben** [saltcorn/saltcorn#1589]
Hi, when trying to build an android app with docker via the saltcorn GUI, after some building time the message "The build was successfully" appears but there is only a logs.txt with the following:

[...]
npm ERR! Log files were not written due to an error writing to the directory: /root/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
    at ChildProcess.whenDone (/saltcorn-mobile-app/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  stderr: "npm WARN logfile could not be created: Error: EACCES: permission denied, open '/root/.npm/_logs/2023-01-24T06_11_07_085Z-debug-0.log'\n" +
    'npm WARN idealTree Removing dependencies.cordova-sqlite-ext in favor of devDependencies.cordova-sqlite-ext\n' +
    'npm ERR! code EACCES\n' +
    'npm ERR! syscall open\n' +
    'npm ERR! path /root/.npm/_cacache/tmp/a0a911b2\n' +
    'npm ERR! errno -13\n' +
    'npm ERR! \n' +
    'npm ERR! Your cache folder contains root-owned files, due to a bug in\n' +
    'npm ERR! previous versions of npm which has since been addressed.\n' +
    'npm ERR! \n' +
    'npm ERR! To permanently fix this problem, please run:\n' +
    'npm ERR!   sudo chown -R 1001:1000 "/root/.npm"\n' +
    '\n' +
    'npm ERR! Log files were not written due to an error writing to the directory: /root/.npm/_logs\n' +
    'npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal\n',
  code: 243
}
No platforms added to this project. Please use `cordova platform add <platform>`.

---

I tried setting the /root/.npm folder's permissions to be owned by the user running saltcorn but it doesn't have an effect.  The log also tells me that NPM ist at Version 8.15.0 but because the locally installed NPM Version is 9.3.0 I think it has something to do with the docker used for mobile building?

Is there something I can do or is this a bug?

---

[...]
npm notice 
npm notice New major version of npm available! 8.15.0 -> 9.3.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.3.1>
npm notice Run `npm install -g npm@9.3.1` to update!
[...]

**Comment by christianhugoch** [comment]
Hi, can you tell me how you did the build?

Did you select the docker checkbox, or is this from the 'saltcorn-with-mobile' docker image? And how is saltcorn installed, from a git checkout or the npm package?

**Comment by christianhugoch** [comment]
I've written a vagrant file to run a build with the docker checkbox clicked, and there was a problem with creating the 'cordova-builder' docker image.

Normally, the image is build while doing a npm install, but I had to re-build it manually.

Can you try to find the Dockerfile and build the image? On vagrant the Dockerfile was at
/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/mobile-builder/docker

and to re-build it:
sudo -u saltcorn docker build /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/mobile-builder/docker \
        --network host -f /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/mobile-builder/docker/Dockerfile \
        -t saltcorn/cordova-builder
(or without sudo, if it's rootless docker)

I hope it helps, otherwise, you can use the '@saltcorn/saltcorn-with-mobile' docker image. It's a complete installation, just like the normal release image, but it has all dependencies and configurations to build a mobile-app.
