### ISSUE TITLE
feat: get the whole current user object in formulas scope

### ISSUE THREAD

**Issue by toomuchdesign** [saltcorn/saltcorn#1638]
**Is your feature request related to a problem? Please describe.**
I have 3 tables:
- **categories** table
- **default users** table where each user has a relational field pointing to a categories table entry
- a **blog post** table where each entry has a relational field pointing to a categories table entry

I'm trying to filter the post listing page page based on current user and current blog post entry having the same category associated.

**Describe the solution you'd like**
I'd like to use custom filtering formulas to do the filtering, but currently only `$user_id` is available in formulas' scope. I cannot get current user's associated categories.

**Describe alternatives you've considered**
I'm considering extending [formulas' scope](https://github.com/saltcorn/saltcorn/blob/8272194ebfd70e3a570659c55305ebd628bdbb83/packages/saltcorn-data/base-plugin/viewtemplates/list.js#L778) with the whole current user object + any custom relational entity (eg. a user category where categories lives in another table).

**Additional context**
In case my client decided to pick Saltcorn I'd be happy to contribute to the implementation. I'm writing to ask whether this could fit Saltcorn's roadmap.

Thank you so much!

**Comment by glutamate** [comment]
Yes I have a plan for making this much more flexible. It's going to be awesome I promise but you are right for the moment you can't do that! The problem is that these equations essentially have to be translated to SQL and that has to be done securely to protect against injecting arbitrary SQL. I think I have worked out how to do this now, I just have to implement it

However if you use "extra state formula" embedding the view into a page you have much more flexibility and you can use the full user object. For instance, say you have a user field called category which is the main category this user is interested in, and you have some BlogFeed view. Then embed the BlogFeed with extra state formula `{category: user.category}`. -this should work

If instead the user is interested in multiple categories you need a join table UserInteredInCategory with fields category and user (both keys to their respective table). I think there is an option, if you create Show view for the User, to pick the relation from the relation drop down that goes through that table.

**Comment by toomuchdesign** [comment]
Hi @glutamate! Thank you for replying to both of my issues 🙇!
I had completely overlooked the `extra state formula` field, and missed that a view could be provided with extra data when embedded in a page. I'm going to give it a try and see how far I can get.

Thank you for the amazing job you're doing here. Saltcorn is probably the best really free and OS low code form tool around!

**Comment by toomuchdesign** [comment]
As explained here (#1639), I created the join table but I had no luck at using it to filter another table. Is there any example documentation I could read in order to find my way around?

I tried to play with `extra state formula` but I wasn't able to retrieve its value from within the filter formula expression.

Thank you so much!

**Comment by glutamate** [comment]
There is now full access to the user object in the row inclusion formulae as of #1738 . This is done by partially evaluating the expression so that e.g. `{id: 5}.id` is reduced to `5` before sending it to the ORM query. Additions between constant terms are also resolved.
