### ISSUE TITLE
Global variables and constants

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1684]
It would be excellent to be able to include variables and global constants accessible from anywhere in the application, as is the case of the "moment" add-on that you can use when creating a calculated field, or when placing a formula text with a date. I do not know well how the source code of Saltcorn is constituted and how it would be the easiest solution, or if there is a solution in sight that I overlooked.

My need arises for example, in the case of a system with accounting parts, and when I have to make calculations with some tax, I should not always be multiplying each time by the value of that tax, and if it varies, have to modify it everywhere in the application.

**Comment by gianlucafiore** [comment]
Is there any way to do this with some other alternative @glutamate? The only one I can think of at the moment is to create a table with a field for each precise value to be referenced as a global variable. and that each table that requires such values has an FK automatically pointed to the first and only value of the global variables table. But it doesn't give me much peace of mind that how healthy this is for the Saltcorn system.

**Comment by JuergenRosskamp** [comment]
The workaroun I am using is that I add a field to the user table and use that a global variable. Just be careful that you always have to set "set user language" in order to publish that and make that available outside the current context.  Backside is that you are not able to change the user language as it was designed for. but for non-multi-language apps that should work.
