### ISSUE TITLE
Unable to download Modules/Extensions

### ISSUE THREAD

**Issue by faisal-abdin90** [saltcorn/saltcorn#1700]
Hello,

Just yesterday I deployed a test instance of Saltcorn using the docker deployment method.
Today while trying to add Modules or plugins via the webUI I am getting an error that there is no response from the Store's API

When I checked all of Saltcorn's website, wiki, forums etc are all down. Is there an issue with the project?
Are there any alternate repositories where I can get the modules or packages?

**Comment by scmsystm** [comment]
Same here, recently installed on Ubuntu Multipass Windows 10, can do anything except opening modules page.

**Comment by glutamate** [comment]
this is now fixed - the server was down. 

The problem here is that the "important" Saltcorn apps (module store, main website, blog, wiki etc) are on the same server (and the same Saltcorn process) that has 17,000 test apps created by users. 

I need to move the critical infrastructure to a separate server

**Comment by faisal-abdin90** [comment]
@glutamate Thank you for the prompt response.
Everything is working as expected
