### ISSUE TITLE
Users are not created when assigning a welcome page

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1827]
assigning a welcome view for new users who have just registered does not create the account for the newly registered user but does redirect the user to welcome view
  
![234442816-842498d9-7dc0-4adc-b3bb-c9d02b06355d](https://github.com/saltcorn/saltcorn/assets/50465150/25713a73-913a-493f-b5f5-6c718f58e6ad)

**Comment by glutamate** [comment]
Fixed in #1989. Now, the new user form (which is now labelled as new user view) is checked if it is an edit or show. If it is an edit, it works as before - the user creation is only completed when the user fills in this form. If it is a show view or another non-edit form, it just redirect to this view after signup so you can use it as a welcome view.
