### ISSUE TITLE
offline support for saltcorn server

### ISSUE THREAD

**Issue by mark-myer** [saltcorn/saltcorn#1881]
Hello,
I wish to run saltcorn on an offline server, but am having troubles with very sluggish performance. I suspect this is from the webbrowser waiting for online resources such as Google fonts. When I connect the server to the internet, performance greatly improves. 

Is there a way to run saltcorn efficiently offline? If it is documented, I must have overlooked it. All I need is to keep the server from inserting online load events into the page.

**Comment by glutamate** [comment]
This should work. Which theme are are using?

**Comment by mark-myer** [comment]
Hello @glutamate,
I am using the default theme: adminlte. This is what I get from browser tools:  

![saltcorn-load-network-report-clip](https://github.com/saltcorn/saltcorn/assets/127981848/5fc8a5bc-2ca1-4125-95b3-9d9a63f6e899)
this is the message: css:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
**link-address:** https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i
Each page took 12s to load. When I activated network blocking on this address, performance increased phenomenally.

Also, if I add any modules not installed by default such as flatpickr-date and then restart the server offline, I get this error message when I start the server: 
![failed-to-load-package-clip-full-error](https://github.com/saltcorn/saltcorn/assets/127981848/c66d42c8-a5f0-464b-9bb2-6b744be064f5)
Any view using module does not work.
Thanks so much for your help and all your work on this platform!

**Comment by glutamate** [comment]
in #1895 the font file in sbadmin becomes self-hosted. (@j2l). 

The problem with the plug-ins is because you are running in docker. I didn't really think about this before, the problem is that the plug-ins are downloaded (while you are still connected) to a directory (`plugin_packages/` in the current working directory where `saltcorn` cli is run. But this is not persisted between docker container runs. If you can figure out how to persist this directory with a volume mount then that will solve the problem.

**Comment by j2l** [comment]
@mark-myer  yes :dev will work, all images are at https://hub.docker.com/r/saltcorn/saltcorn/tags
