### ISSUE TITLE
Feature Request: Add Field over PNG of document

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#1926]
How do I move a field in a edit view over a PNG of a document? I must be missing something. I cannot add to a top layer over the PNG. Everything is on the same layer.

**Comment by Ingenu1ty** [comment]
It looks like the "layers" in the visual editor aren't layers at all🙃, at least they're not photoshop-like layers. It's more like a visual representation of element nesting...(although I could be wrong, I'm a newbie here too😏) 

So if I'm right, then a workaround in your case could be to use custom css with [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) 

...So, given the above, "True Layers" with the ability to adjust z-indexes in the visual editor sounds like an idea for a feature request for your case😏

**Comment by serge402** [comment]
@cfredericksen Use "Contain" under Components, then in the Container settings go to Contents -> Background.

There you can set image/colour/gradient with repeat, etc...

**Comment by cfredericksen** [comment]
> @cfredericksen Use "Contain" under Components, then in the Container settings go to Contents -> Background.
> 
> There you can set image/colour/gradient with repeat, etc...

Thanks for the reply, @serge402. I added my PNG and set it as a background in a container. But the PNG is a tiny thumbnail. I changed the background width to 600 but its still tiny. I am not sure I could add a field over the container in a specific location.

**Comment by serge402** [comment]
@cfredericksen Could you attach the PNG to your next post and a small sketch of what your trying to achieve and I will attempt to recreate it. 

Then I can display the layout for you to follow.

**Comment by cfredericksen** [comment]
![I-9-1](https://github.com/saltcorn/saltcorn/assets/45824775/5682da64-61ba-489b-a7aa-42899ef1d97d)
Here is a I9 form. I want to add a Saltcorn field over each field in the form. Thanks for the help! @serge402

**Comment by serge402** [comment]
@cfredericksen That's not what I expected, you might be better (faster) off simply re-creating the Form.

However, I will still demonstrate the overlay way.

1. Create a Container and all the Image to it: Contents -> Background -> File: (png File), Size: "cover"
As this stage the image will be small.
![image](https://github.com/saltcorn/saltcorn/assets/66882139/fa67c523-ae50-4890-8e83-571ee0b6272a)

2. Add Another container within that original container (one with image), and this time add a Test field into it.
![image](https://github.com/saltcorn/saltcorn/assets/66882139/cc4f77da-b676-48f7-b4bd-a9c80967d502)

3. Use the Box option within the second Container (one with Text) to move the text around, add Top Padding to drop it down and Left padding to move it right. (You can use other options if you understand the Box html/css model)
![image](https://github.com/saltcorn/saltcorn/assets/66882139/3e41a6e5-f3a0-462d-91ce-4efa74cb9f1d)

4. For another field you want to add, simply make another Container within that original container (one with image) and as before add a Test/Input field into it.
Then as before you edit the Box -> Padding (of the Container) to simply move the position of the field. 
(Make sure you set Display -> Display: inline) Otherwise it will place the new container on a new line.
![image](https://github.com/saltcorn/saltcorn/assets/66882139/563e6859-dc81-4443-9c27-6b00a7807e99)

Should look something like this:
![image](https://github.com/saltcorn/saltcorn/assets/66882139/52e30c6d-9af4-4b95-86d2-a56452f2392c)

Then just continue adding more fields as you need, and simply put a Container in the bottom to display the whole page.

This is definitely time consuming deepening on how many fields you need to add and as I said before, you might be better off re-creating the whole Form.

Let me know if this helps or if you have further questions.

**Comment by serge402** [comment]
@cfredericksen Did this solve your problem?

Do you want to close the Feature Request?
