### ISSUE TITLE
Passing parameters to client page action run js code?

### ISSUE THREAD

**Issue by hainecki** [saltcorn/saltcorn#2083]
I need to run action that authenticates in external api, receives a link to pdf file from this api and opens it in browser window, based on link with token, but also access to document - opened session, is required. In Saltcorn I have data in table and each document has unique number which may be useful to send request to abovementioned api method. I think the simplest way is to run action on the client page. But I don't think I can on the beginning pass data from table row to action run_js_code running on client page by simply running it as action on row. Is it achievable in any other way?

**Comment by glutamate** [comment]
if you run a run_js_code action from a Insert/Update/Delete event OR a view where it's related to a specific row - action in list or in show -  you can use the `row` variable inside the code to access the row it is running on. So if your table has a field "Doc Unique Number" (which will have variable name doc_unique_number as you can see in the list of fields) then inside the code you can access `row.doc_unique_number` or just doc_unique_number. Note that this will not be accessible if you do a test run because there is no row to associate to.

If you want this inside a page, can you embed a show view inside the page (use something like `{id:1}` as the extra state formula to show a specific row). 

Does this help? or maybe I haven't understood the problem.

**Comment by hainecki** [comment]
Thank you. The exact problem is variables are not in scope when running on the client, the same as issue #2076

**Comment by glutamate** [comment]
working on this

**Comment by glutamate** [comment]
implemented in #2088

**Comment by hainecki** [comment]
Thank you
