### ISSUE TITLE
please add a Show-if-True condition to the "use view to create"  in step 2 of a list-view configuration

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2228]
It would make things so much easier when this show-is-tue can prevent user from adding rows to tables when a join-field in the master-record has a certain value.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/930f3f86-2bea-40da-be5a-2f604b49e7c7)

**Comment by Ingenu1ty** [comment]
I think [it's not that easy to implement](https://github.com/saltcorn/saltcorn/issues/2150#:~:text=Dec%207%2C%202023-,It%27s%20difficult%20to%20have%20an%20equation%20here%20because%20there%20isn%27t%20a%20single%20row.,-If%20you%20are) **until** something [like this](https://github.com/saltcorn/saltcorn/issues/2150#issuecomment-1846766156) is implemented... 

But I think you can try using [the validate event](https://github.com/saltcorn/saltcorn/blob/503c3cdd0506bb3dc3acbcd672bc076c3e13527f/packages/server/help/Event%20types.tmd#L19) as a **workaround**. Instead of conditionally hiding the "use view to create" link, simply prevent users from adding a new row if your conditions are not met.

**Comment by glutamate** [comment]
@HFolkertH @Ingenu1ty I can do a show if formula based on the state (whats in the URL query string) and the user - but not a join field or data from the database tables. Would that help?

**Comment by HFolkertH** [comment]
hi @Ingenu1ty 

Thanks for helping me out.
Using this validate event means that the user already entered lots of data and after he has clicked the Save-buton  then he is notified that is was all for nothing.  Not so user friendly.

**Comment by HFolkertH** [comment]
hi @glutamate,

I can give it a try. How to I place an extra field in the Url?

**Comment by glutamate** [comment]
@HFolkertH insert anything in an extra state formula. this can be a field on the table but this will filter the list contents. you can also just insert dummy data that will be ignored if it does not correspond to a filter: `{some_name: 5}`

instead of 5 you can use true/false or a string `{some_name: "hello"}`

**Comment by HFolkertH** [comment]
Ah, I get it. Thanks!

**Comment by glutamate** [comment]
Would it be useful if add a show if formula based on the state?

**Comment by HFolkertH** [comment]
Yes please!
thanx in advance

**Comment by glutamate** [comment]
implemented in #2236

**Comment by HFolkertH** [comment]
Hi @glutamate ,

i tested it in many ways but i can not get it to work. If I put the value true or false in the expression it works as I hoped. 
But every other expression (even your !!row.createlink) always returns a true. Are the expressions evaluated? 

 I test it on the project-managent pack where i give the project an extra status-field (“Open” or “Closed”). Only for open project adding new Todos should be allowed. Can you show me a screenshot how a good working show-if-formula supposed to be used? Thanx

BTW really love Saltcorn and how it makes use of the ERD to create functional data entry views. The best low-code tool currently on the market. And I experimented with 100 or so.

**Comment by glutamate** [comment]
Example how i tested it: 

If i have a view called mylist with Show if formula = !!row.createlink

then if i visit URL /view/mylist there is no link to create, if i visit /view/authorlist?createlink=1 there is a link to create.

In a page, if i embed the view alone there is no link. If i add extra state formula `{createlink:1}`  or` {createlink:true}` there is a link

If you are embedding in a show on a table and want to use the view to show related rows with sometimes a create link based on a field, use something like `{createlink:myfield}` in the extar state formula for the list embedded in the show, with the right relation.

**Comment by glutamate** [comment]
@HFolkertH So in your example probably {createlink: status === "Open"}

**Comment by HFolkertH** [comment]
hi @glutamate 

Thanx for the hints. I will certainly try them. 
But what is this "!!"? I can not find it on the W3school article about JS comparisons.

**Comment by glutamate** [comment]
this is just applying ! (not) twice, turning a truthy value into true and falsy into false. Because if the expression returns undefined or null, the show if formula will be shown (if user has permission to write to table)

https://stackoverflow.com/a/29312197

**Comment by HFolkertH** [comment]
hi @glutamate 

Your hints about using the new Show-if formula for the create link in List-views worked perfectly. Thanx! 
Now a user can only add Todos to open Projects
