### ISSUE TITLE
Does an "on change action" in an edit-view pass its context to it's associated action? It seems not.

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2295]
**Describe the bug**

Trying to use  on-change-action to give field-2 an initial value when field-1 changes.
I have an action defined (run_JS_code on server-side)   in the events/triggers but that action does not receive any context from the edit-view from which that on-change-action was triggered. Is that correct?
On client page the script receives a context (although the text "variables in scope: ?" suggest otherwise )but there I am not allowed to use Table.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/aada0364-049b-4318-8e62-70fdfbfeda7a)

**Expected behavior**
seeing some scope and being able to use set_fields() to change a variable in that scope

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/22573455/8ef6fee7-c1f8-4d74-8f55-7e51a094677b)

**Additional context**

**Comment by glutamate** [comment]
1. Is there still seemingly a bug @HFolkertH  ? When i am inside an "On change action" i can access both `row`, `table` and `Table` and it all seems fine. `row` is the full row.

3. To set other field values, in a run_js_code (run where = Server) use this:

`return {set_fields: {myField: thenewValue}}` 

the new value expression can be a constant, or a javascript expression depending on `row`

normally you can also use modify_row action and set modify where = Form, but in field "on change action" you don't have the ability to configure actions so that won't work
