### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by igorkb** [saltcorn/saltcorn#257]
How could I translate Saltcorn? Is there a way to create translations besides hardcoding, so that different users could select different languages?

**Comment by glutamate** [comment]
Thank you for raising this, it is a really important point. Right now, there is nothing related to translation. I think there are 3 different questions:

1) how can we provide translations for the strings hardcoded in the Saltcorn codebase. This would allow you to build an application in a single non-English environment.
2) when building an application, how can text be specified in multiple languages. This would be important for people building applications for multiple languages.
3) how can user generated content be translated into multiple different languages.

I think 3 is just too difficult right now. Let's ignore this until 1+2 are solved

I will look into how I can do 1 first. This will probably lose points of the direction towards a solution for 2.

**Comment by glutamate** [comment]
I've done the basic translation using node-i18n. It was very straightforward. The translation files are created with Google translate, so I expect many of the translations to be wrong or downright ridiculous. 

This is done for the following locales: "en", "fr", "de", "da", "es", "no", "sv", "ru", "nl", "pt" - translation files are in this directory: https://github.com/saltcorn/saltcorn/tree/master/packages/server/locales it should be very easy to edit them.

I have deployed on saltcorn.com, please test. In order to get it in your favourite language, you will need to tell your browser what your language preference is. I expect some failures and will be watching the crash log.

That basically concludes point 1 from my above comment. I think I have an idea about how to do point 2, but that is more difficult both in the UI and in choosing the appropriate language on the backend. For the hardcoded strings it was really easy, it's all done for you as if by magic but that won't work as easily for point 2.

**Comment by AleksandrSokolov** [comment]
@glutamate I just added basic description of translation to wiki: https://wiki.saltcorn.com/view/ShowPage?id=31

Because i was done it using smartphone  it is not very nice.
Please put the link to this page from main pages.

**Comment by AleksandrSokolov** [comment]
@glutamate About the mentioned points.

1. Thanks. You are very rapid in adding new features. 

May be the long string keys is not very cool solution but for the moment it works fine.

2. There are no easy answer to do this. May be wiki application is good start point to experiment with this. Because  wiki usually can have few different language variations of same page.

About technical realization. Few options.
Needs protyping or find great solution in other projects.

**Comment by igorkb** [comment]
> The translation files are created with Google translate, so I expect many of the translations to be wrong or downright ridiculous.
Oh god it is horrible! hahaha

> In order to get it in your favourite language, you will need to tell your browser what your language preference is.
It's strange how the website selects the language without letting me choose.

I was busy for the last 2 days, but i will take a look tonight (GMT -3) and try to translate some things.

I am a industrial designer (who also runs a bakery) and i know little to nothing of JS (I mainly use Python and a bit of Lua), but i can work on the translations to Brazilian Portuguese, Italian, French and a bit of Spanish.
