### ISSUE TITLE
Multi tenant not working correctly?

### ISSUE THREAD

**Issue by Zickezack** [saltcorn/saltcorn#2593]
Hi devs, we are trying to set up a multitenant environment for around 90 students and just stumbled upon the multitenancy variable. We are trying out Saltcorn 0.9.6-beta.19 running with the example deploy compose provided in the repo on localhost. Only change is the multitenancy variable (- SALTCORN_MULTI_TENANT=true) in the environment variables of saltcorn-app.

I created a public admin and then from the site admin two tenants. I can see when prompting the DB that they each get their own schema and tables (e.g. a new users table with schema "firsttenant") in parallel to the already existent public tables. When I however head over to the tenant subdomain (e.g. firsttenant.localhost:3000) and either register a new user or login with the public admin to create a local admin, the new users will always be listed in the public users table and not in the users table with schema "firsttenant". It will be possible to login with the newly created user in the subdomain "firsttenant.localhost:3000", but anything created will then be registered as a public schema table and not tenant specific.

Are we doing something wrong or is this a bug?
I am not sure if or which further information is needed so I will just provide it as required.

Best regards

**Comment by christianhugoch** [comment]
Hi, the tenant gets extracted from the url and this happens when you use localhost. On saltcorn.com for example

https://christians_test_app.saltcorn.com

gives you: christians_test_app

But to make http://christians_test_app.localhost:3000 work, you can either change your /etc/hosts file or the saltcorn serve command.

I believe in the /etc/hosts you could make something like this
127.0.0.1 example.com sub.example.com sub1.example.com sub2.example.com sub3.example.com sub4.example.com sub5.example.com sub6.example.com

And for the saltcorn serve call you can change it to

saltcorn serve -p 3000 --subdomain_offset=1

Does this help?

**Comment by Zickezack** [comment]
Thanks, this solved it. It's helpful that I can now test out tenant deployment on my laptop before deploying on our server.

Do you perchance also know a way to instantly deploy let's say 90 tenants? I know I can use templates, but still have to create it manually. I know it's a niche case and if I must do it manually, that is ok.

Best regards and thanks for the help

**Comment by christianhugoch** [comment]
and after that
saltcorn create-user -t testtenant -e "admin@foo.com" -p yoursecret

**Comment by Zickezack** [comment]
Thanks for the suggestion - I will try it next week because I will be absent. 

Question well answered and therefore I'll close this topic.

Best regards
