### ISSUE TITLE
Restore from backup does not work after "clear all"

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2609]
**To Reproduce**

1. press "clear all"
![Scrs11](https://github.com/user-attachments/assets/6f99b6a0-c3e3-46e8-bf4f-1cb0121c3379)
2. on the start page upload the backup
3. see errors

**Comment by glutamate** [comment]
thank you @Ingenu1ty. This is bad, fixing. Is it only the error about role_id you see or are there others?

**Comment by glutamate** [comment]
fixed in #2614, at least for the errors i see

**Comment by Ingenu1ty** [comment]
> Is it only the error about role_id you see or are there others?

After I discovered this bug I tried a few more restore cycles from backup...
I assume that there **may be problems** if you restore from a backup to a non-empty SC instance(with an **existing tables structure and views**) especially if the tables and views names from the backup **match the names** from the existing SC instance.
or make a backup, delete some(not all!) tables and views, and restore from the backup... 

although I'm not sure that these problems are not the result of the original bug... because after restoring from backup everything became a mess and I deleted that buggy test setup...

**Comment by Ingenu1ty** [comment]
I think it would be useful to provide playwright testing coverage of the functionality related to backups(and Snapshots and packs) 

especially in **tricky cases**, such as complex connections and **ownership relationships** -> delete one of these tables (but leave the view based on it) -> restore a snapshot containing the name of the deleted table, and so on... 

I think it's important to think about such cases because these kinds of bugs can **potentially** throw all the data from tables into chaos...

**Comment by glutamate** [comment]
@Ingenu1ty Playwright isn't really the best place to put tests of lots of different types of configurations, because it is very time consuming to set up different cases when you can only interact with UI. the jest tests are better for that, because you can programmatically set up different views, different situations. I put a restore after clear all test in there when i fixed this. We just had another backup failure and i put in a jest test to make sure that doesn't happen again. The backup test is here https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-admin-models/tests/backup.test.ts
