### ISSUE TITLE
Incorrect behavior - The project name is not shown in view todoedit

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#273]
![image](https://user-images.githubusercontent.com/327030/94016911-6b581a80-fdb7-11ea-8279-32b47a0731fa.png)

**Comment by AleksandrSokolov** [comment]
The todo was added from the project and after "Save"  was stored with correct link to the project.

**Comment by glutamate** [comment]
It is sort of behaving correctly, because the project comes from the query string and as you noted is set correctly.

However I think this was a poor design choice because you have no way in the builder to hide the label depending on whether it is set. Also, the user may not feel comfortable about setting values in the database that come from the query string without seeing the value.

I will stop hiding these values that come from the query string and show them as normal (but still preset to the value specified)

**Comment by AleksandrSokolov** [comment]
@glutamate , ok, thanks

**Comment by glutamate** [comment]
fixed in #277
