### ISSUE TITLE
Feature - [viewedit/config/] 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#330]
![image](https://user-images.githubusercontent.com/327030/95891046-32dfa700-0d8d-11eb-9033-7b5e5d0aa20d.png)
Add ability to generate link for this field.
This link will open the Edit View for this record. 
![image](https://user-images.githubusercontent.com/327030/95891105-4428b380-0d8d-11eb-9ea2-e1dd533882e8.png)

**Comment by zinkh** [comment]
This can be grouped with #306 it is the same issue, aybe this can be done with the link feature @glutamate is working on.

**Comment by AleksandrSokolov** [comment]
@zinkh I agreed with you.

**Comment by glutamate** [comment]
@AleksandrSokolov @zinkh with recent comments you now have a couple of options:

1) the view link option as a column in the list view is now bit more flexible and you can tick the box to interpret the view label as a formula which means that you can use JavaScript expressions to calculate the label.

2) (this was there previously) if you try to leave the view link label blank, in some cases (if it is a link through a foreign key in the current table) it can use the summary field from the linked table as the label from the view. Just try to leave it blank and see if it does what you want

3) you now have an option to have plain links as a list column. (I think it's titled "Link to anywhere"). Here you give the text and URL and can choose that both of these can be interpreted as formulas, ie JavaScript expressions. In fact it only really make sense if at least one of them is a formula, otherwise you will get the same link in every row

**Comment by AleksandrSokolov** [comment]
@glutamate great news. We really need to organize documenting process. You done a lot of thinks but documentation is poor for now.

**Comment by zinkh** [comment]
That's really great, thanks for this update. It's so much better now, I just made a simple formula in a contact view, the formula is 'edit' + ' ' + name_in_table and it shows something like : Edit Mike. This is so Powerful, now I have to think about a couple of formulas and some usage cases.

**Comment by glutamate** [comment]
@AleksandrSokolov agree on docs. really we need 1 wiki page per view template and also more docs for individual plugins
