### ISSUE TITLE
Issue: [List View][Edit View] Few problems in case of 2 relations between 2 tables

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#348]
Incorrect presentation in List View.
![image](https://user-images.githubusercontent.com/327030/96217645-b6ff7d80-0f8b-11eb-92b8-4495b334893b.png)
 In reality supplier and manufactor are null for 2 first Products.
![image](https://user-images.githubusercontent.com/327030/96217941-57ee3880-0f8c-11eb-9c46-638ab9c5afa1.png)

Aslo I find other issue - Incorrect choose of manufactor in Edit View. Instead of manufactor we see choose from products
![image](https://user-images.githubusercontent.com/327030/96217818-165d8d80-0f8c-11eb-8edf-27d9cda4e91f.png)

Reproducing: https://uat_reproducing_errors.saltcorn.com/view/Products

**Comment by glutamate** [comment]
Thanks @AleksandrSokolov. this sounds serious - will have a look

**Comment by glutamate** [comment]
yes, of course now i understand why this is happening. hmm...

**Comment by glutamate** [comment]
I think this is correct now. The problem was obviously the "name" field name which was present in both the products table and the company table. This is now fixed in #350. This was a great test and obviously challenged some assumptions I've made during the build. We now have a unit test for this.

As to the 2nd problem you mention, I'm not sure it really is a problem (or maybe it was but also fixed now). Manufactor in the  drop-down picks Products (manufactor field is Key to Product) - as far as I can tell this is correct, at least now after #350 is deployed.

**Comment by AleksandrSokolov** [comment]
@glutamate thanks. It works for me.
I corrected the test case: 
![image](https://user-images.githubusercontent.com/327030/96298868-d59d5d00-0ffb-11eb-9777-4fb97860a877.png)

**Comment by AleksandrSokolov** [comment]
@glutamate but for me still question how to update my installation)) if you doent create new npm package

**Comment by glutamate** [comment]
@AleksandrSokolov ok, i can release a new npm package

**Comment by glutamate** [comment]
@AleksandrSokolov 0.2.3-beta.0 is ready

**Comment by AleksandrSokolov** [comment]
@glutamate Thank you!
