### ISSUE TITLE
Feature: [useradmin/]Admin functionality to reset user password and create user without password

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#352]
Idea is:
1. New flag for existing users "Generate password and send to email" (reset password).
If admin sets this flag then Saltcorn generates password and sends it to user email box.

2. New flag at the moment of creation user "Generate password and send to email".
If admin sets this flag then Saltcorn generates password and sends it to user email box.

This is usefull for mass create new users and allows to not spent time for transfer password from admin to user.

**Comment by glutamate** [comment]
This is implemented in #378 , as you described except instead of sending passwords on email, we send the reset password tokens so the user can reset their password. I think this is a bit better because if plaintext passwords are in emails, and we don't force people to change them, then old emails may give away the credentials for login. On the other hand the reset password tokens expire.

Let me know if this works for your workflow @AleksandrSokolov. I will release a new beta later today

**Comment by glutamate** [comment]
0.2.3-beta.2 is released

**Comment by AleksandrSokolov** [comment]
@glutamate Yes, the reset password token is better. Thanks
