### ISSUE TITLE
[Feature request] Show Id in tables or formula for auto-increment

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#369]
Hi @glutamate.

I know all entries in tables have an Id number so it can be identified when opening on a show view for example. 
It can be interesting to show this id as a table column, if it's not possible maybe we can set manually a column called ID or KEY or NUM, then we need a formula in calculated field so it auto-increment for each new entry.

Thanks

**Comment by glutamate** [comment]
agree. we ned to be able to use the id in several places

**Comment by glutamate** [comment]
Implemented in #374 (not yet merged). If the variable is stored, sometimes `id` will be undefined (when creating a new row) , sometimes it will be filled in (when updating a row). Because this inconsistent, I have excluded it from the example list of variables for expressions for stored calculated field, but shown it in the example list for non-stored calculated fields.
