### ISSUE TITLE
Feature: Option: User UUID/GUID instead of Int for ID fields in tables

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#372]
Reasons:
1. Using of UUID is first step to create microservices based on Saltcorn tenants.
2. UUID is wildly unique and you can without problems migrate records between different few tenants if you have same table in few tenants.
Implementation:
1. Add optional flag when create table to use UUID for ID / May be better to show ID column in list of colums and allow to change it type between Int / UUID as minimum.
2. Add flag for Saltcorn configuration "Use UUID for ID" that forces Saltcorn to use UUID instead of ID.
3. UUID doesn required PG sequence and nativelly supported by PG https://www.postgresqltutorial.com/postgresql-uuid/

**Comment by glutamate** [comment]
I agree, this is very exciting, in particular for me because it opens up the possibility of distributed applications that might get synchronised. For instance if you are building apps for people to use on mobile devices not always connected, people can add rows on those devices without fearing a clash with the central server or other devices.

The only problem is that allowing UUIDs as ids is of course some work. But maybe not too much. I definitely wouldn't be able to support switching tables from int pks to UUIDs

**Comment by AleksandrSokolov** [comment]
@glutamate nodejs is new for me but I'll try to help you

**Comment by glutamate** [comment]
Work in progress branch here https://github.com/saltcorn/saltcorn/tree/uuid-ids if you want to take a look @AleksandrSokolov

**Comment by glutamate** [comment]
implemented in #590 - need to install uuid-types plugin, then you can switch the type for the id field to UUID if there is no data in the table.
