### ISSUE TITLE
Feature: External tables concept for calling rest services / connects to mq / other tenants

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#373]
The idea:
Implement on Saltcorn level concept of external tables.

Main purposes:
1) Access to tables in other tenants via rest - this one of the steps to do microservices on Saltcorn base and also will allow to get advantage for having single reference tables for few tenants.

Examples:
* unified user list for few tenants
* unified country list for few tenants
etc.

2) In https://en.wikipedia.org/wiki/ClickHouse is very cool concept of external tables (https://clickhouse.tech/docs/en/engines/table-engines/ See Integration Engines).

Example of usage:
* create integration with some Message Queque broker Kafka, ect
* call some external service for example to get currency rate or country list

Later I can explain more about idea

**Comment by glutamate** [comment]
Yes, I've also thought about this, for a different application: I was thinking about exposing the linux process list, systemd units and  logs as external tables to allow you to build a system administrator dashboard. The way to do this, which would include your use cases, would be to allow plug-ins to define virtual (or external, as you call them) tables. I got stuck in this because I didn't know how to handle joins, but maybe we can just say that you can't join onto these tables or define some minimal join functionality. 

The other way of implementing this is making everything go through postgresql with fdw functionality.

**Comment by mshiner** [comment]
This would be interesting to allow integration with uzERP.

I'd like to define a uzERP table (or a view) as a lookup on a field (poss a FK constraint but not always).

Example.... I'm looking at a use-case for a uzERP user where they want to add extra data against customers - its a single table application but the customer id field in the saltcorn table needs to 'look up' the customer from a table/view in the public schema.

**Comment by glutamate** [comment]
email with IMAP is a great use case for this.

**Comment by glutamate** [comment]
read-only texternal tables added in #601 

I have a working example in the system-info plugin
