### ISSUE TITLE
Feature: Tag cloud field type (plugin)

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#428]
The example
![image](https://user-images.githubusercontent.com/327030/99918067-7bdc3100-2d25-11eb-8ff0-7eb8e88e77c0.png)

The basic functionality already implemented in:
![image](https://user-images.githubusercontent.com/327030/99918092-b776fb00-2d25-11eb-8003-f719d8ee7b11.png)

**Comment by glutamate** [comment]
We have this. it is the "badges" plugin - that reminds me, i need to make this a bit easier by adding some explanatory text

Maybe i will also make a wiki page with plugins overview

**Comment by AleksandrSokolov** [comment]
@glutamate yes.  thanks you. Really needs more explanation about power features hidden:-) in plugins.

**Comment by AleksandrSokolov** [comment]
@glutamate in my not native english world this named tags)). ok. let me try to use

**Comment by AleksandrSokolov** [comment]
@glutamate  I trylly cannot understand how to use this badges plugin... Needs some explanation

**Comment by glutamate** [comment]
@AleksandrSokolov I added a bit more explanatory text to where the badges are configured and I also started writing the wiki pages describing some of the plugins: https://wiki.saltcorn.com/view/ShowPage?title=Some%20useful%20plugins. 

But I'm thinking that maybe some of these descriptions and screenshots should live in the plugin store

**Comment by zinkh** [comment]
This was also described here : https://github.com/saltcorn/json/issues/3#issuecomment-711427977

**Comment by AleksandrSokolov** [comment]
> This was also described here : [saltcorn/json#3 (comment)](https://github.com/saltcorn/json/issues/3#issuecomment-711427977)

thank you for help

**Comment by zinkh** [comment]
For the moment the badges view is only usable in "show view", is it possible to add the ability to use it in "edit view".

Also in the views creation, one thing that can be complicated for new users is that some views are standalone, while others need to be inserted into other views, maybe the later can be renamed to something else (viewparts for example) so it is more straightforward for new users.

**Comment by glutamate** [comment]
@zinkh it's a bit messy because edit views sometimes edit an existing row, which has been assigned an ID, and sometimes creates a new row, which does not have an ID. In the former case we could in principle have the EditBadges, but in the latter case it is more difficult. I think a solution could be found but it is more difficult. 

With respect to the two types of use, there is in fact only one type. You can show the badges on their own, for instance you can link to it from a list. However I realise that this is mostly theoretical and in practice some view templates are used alone and others are used as parts. I'm thinking about how to add a bit more explanatory text to the form where you select the view template.
