### ISSUE TITLE
After adding ssl, can no long access tenants

### ISSUE THREAD

**Issue by jekroll555** [saltcorn/saltcorn#492]
Following adding the ssl module from the Admin page and restarting I can no longer access the tenants I have built. Added a new tenant and cannot access that either. The original works as expected, seems just to relate to the tenants.

**Comment by glutamate** [comment]
Yes unfortunately the SSL certificate obtained is only for single domains. Let's encrypt in principle can issue wildcard domain certificates but this is much harder to set up and I can't just enable it in Saltcorn - you need to be able to modify the DNS settings to obtain the certificate. 

If you want HTTPS on a multitenant instance, I recommend the following:

First switch off the let's encrypt certificate so you can access your tenants again. You can do this by going to the configuration page under settings, go to the very bottom where it says let's encrypt enabled, and then press the trash icon to the right for that line. After doing this you should restart the server under settings -> admin

Cloud flare can give you a free SSL certificate if you use them as the name server, even if you use their free tier. This is what I do for saltcorn.com - it is not ideal because traffic between the cloud flare instance and the server is not encrypted, only traffic between the users browser and cloud flare is encrypted. Read more here: https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options

If you have purchased a wildcard certificate for your domain (these are more expensive than ordinary certificates) we can look at adding functionality to Saltcorn to use this, or if you know how to, you can put a proxy like nginx in front of Saltcorn. It also looks like it's an option to get cloudflare to issue a free wildcard certificate (the origin CA certificate) which we could make Saltcorn support. Let me know if you want to pursue this, I did want the to add the ability to use custom certificates anyways

**Comment by glutamate** [comment]
This is now described in a wiki page https://wiki.saltcorn.com/view/ShowPage?title=HTTPS%20traffic%20with%20LetsEncrypt

**Comment by jekroll555** [comment]
Thanks for the update. I have everything restored per your instructions.  I think I'll probably end up using the Cloud Flare certificate after I get further into development. The wiki you wrote is exactly everything I ran into. Thanks for your help and keep up the great work.

**Comment by glutamate** [comment]
custom ssl certificates implemented in #494 , docs https://wiki.saltcorn.com/view/ShowPage?title=HTTPS%20encryption
