### ISSUE TITLE
Problem: [List view] When I tried to use color columns I cannot use List view 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#540]
Reporduced: 
* list view https://uat_reproducing_errors.saltcorn.com/view/ColorsList
* table https://uat_reproducing_errors.saltcorn.com/table/9

The Scenario is:

Table with color column.
I cannot create List view that shows all records (with all values of color fields including null):

![image](https://user-images.githubusercontent.com/327030/105099773-418cd700-5abd-11eb-8f50-442b069d2f54.png)

Table data:

![image](https://user-images.githubusercontent.com/327030/105099862-65501d00-5abd-11eb-80e1-a652b2d206eb.png)

Table definition:
![image](https://user-images.githubusercontent.com/327030/105099814-51a4b680-5abd-11eb-9064-04c66abd52de.png)

The problem in "Default search form values when first loaded"
Because there are no option to do not set color column for first load.
![image](https://user-images.githubusercontent.com/327030/105100107-da235700-5abd-11eb-9e7c-5fc7c7566ee3.png)

**Comment by glutamate** [comment]
fixed in #543. If the default colour, #000000 is selected, it is assumed not to be a required default state field. This isn't an ideal implementation, but I find it unlikely that someone will want to have a default filter based on colour anyways. Unfortunately HTML 5 colour inputs cannot be left blank https://stackoverflow.com/questions/14943074/html5-input-colors-default-color
