### ISSUE TITLE
Issue: Webhook not sending json

### ISSUE THREAD

**Issue by jekroll555** [saltcorn/saltcorn#567]
Added webhook for insert on Leads table using Landing Page plugin. Webhook fires when lead added to table, but json payload not being sent.

**Comment by glutamate** [comment]
Hi John, I can't replicate that, it works for me. I define an insert web hooks for table and use a url from https://pipedream.com/ (I got this by setting up on https://requestbin.com/, it's a free service) - I see the body. In the configuration for the webhook, you have to fill in the URL and leave the body field blank. Make sure you don't leave any spaces in there, otherwise it will treat that as the body and send that instead of the row

**Comment by jekroll555** [comment]
Thanks Tom, I'm using integromat.com, I have another webhook that works
fine. I did send a json test string through and it worked well. I'll
recreate the webflow and see if that works out.

**Comment by AleksandrSokolov** [comment]
@jekroll555 Please update title of issue with short explanation of problem.

**Comment by jekroll555** [comment]
After recreating everything worked as expected. I had sent test data through before and cleared it, there must have been a trailing space left behind. 
Updated isssue title.
