### ISSUE TITLE
 function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#693]
Hello again @glutamate 
I don't get how to automatically get a new ID.
I though UUID would fix it, but it looks like it failed to install:
![image](https://user-images.githubusercontent.com/65325/114705864-832dc680-9d28-11eb-9c31-3f09a080fdd1.png)

**Comment by glutamate** [comment]
If you are using saltcorn.com, this has now been fixed

If you are self-hosting, You can run the following command as root: `sudo -iu postgres psql -U postgres -d saltcorn -c 'create extension if not exists "uuid-ossp";'`

if you are self-hosting on digitalocean and don't know how to use SSH, I can't do anything about your existing droplet. When the droplet is next updated (following commit https://github.com/saltcorn/saltcorn/commit/476d462d85f77ad6b50e6ac0f765a2bd91a8af99) You will need to backup, create a new droplet, and restore)

**Comment by j2l** [comment]
Thanks!

**Comment by j2l** [comment]
@glutamate unfortunately it's not working on a container (no sudo, already root).

**Comment by j2l** [comment]
Within the container, I tried:
```
root@3b48c5b5b1bb:/opt/saltcorn/packages/saltcorn-cli/bin# ./saltcorn -c 'create extension if not exists "uuid-ossp";'
 ›   Error: command -c not found
```
@glutamate not sure why the bin on the container doesn't recognize `-c`

Any other way to add it?

**Comment by j2l** [comment]
OK, my bad, it is working in the db container using:
`su postgres`
psql...
I get
```
NOTICE:  extension "uuid-ossp" already exists, skipping
CREATE EXTENSION
```
So I guess it is installed, but uuid is not generated when adding a row through:
![image](https://user-images.githubusercontent.com/65325/135299128-ddc53a18-bd9b-4111-966d-bbc998413174.png)

**Comment by j2l** [comment]
Is the uuid_generate_v4 postgres function looks like that in a working environment using Adminer (public > routines > alter)?
![image](https://user-images.githubusercontent.com/65325/136556857-c6585ec9-977a-4bd4-a549-76de37d0a720.png)


No length?

**Comment by j2l** [comment]
Tested on a brand new 0.6.0-alpha.0Latest
By default, it's not present in a slatcorn-db container:
![image](https://user-images.githubusercontent.com/65325/136557983-30d9a8e0-deaf-4e06-8484-bbf50247ca65.png)


Once installed, it looks like the function is working in postgres server itself:
![image](https://user-images.githubusercontent.com/65325/136557331-d3de70e0-7a96-4de7-9a8f-7b43a1364437.png)


After installation I restarted both containers.
Only saltcorn still doesn't use it.

**Comment by glutamate** [comment]
I am not 100% sure about these things, but this is what I think: 

after you have reset the scheme on the command line with `saltcorn reset-schema` (possible running this inside docker with `docker run`), you should run the sql command `create extension if not exists "uuid-ossp";` as the postgres user (i.e. the database superuser) in the `saltcorn` database. This could be done with the database admin tool you use. But saltcorn cannot do this on its own because it does not have database superuser access

See what happens here in the digital ocean image creation: https://github.com/saltcorn/saltcorn/blob/master/deploy/digitalocean-marketplace/files/var/lib/cloud/scripts/per-instance/01-set-secret#L21

This is last thing that happens before the process is started and made available for the user.
