### ISSUE TITLE
Timeout with huge csv import

### ISSUE THREAD

**Issue by bjoliveau** [saltcorn/saltcorn#720]
Hi

I need to import a huge csv (~5 millions rows and ~550MB size file).

Do you know if I can set a timeout?
Either, could you describe the path in DigitalOcean image to import via SQL with Posgresql?

Many thanks

**Comment by glutamate** [comment]
Timeouts are adjustable in #736 (Settings -> Users and Security -> Settings -> HTTP timeout (s) ) 

However, there are other issues with large CSVs - working on it

**Comment by glutamate** [comment]
CSV import performance is much improved in #736. For small CSV files and for all files when using the SQLite database, performance is improved by reading the file only once instead of three times. For files larger than 1MB when on PostgreSQL we switch to using a streamed COPY for import which is _very_ fast. I tested with a 5M rows file, 250MB and the import time is completely dominated by the upload, the ingestion is almost instantaneous (compared to the upload at least). 

There will be many other pain points when you using Saltcorn with large tables, least now we can start finding out what they are!

**Comment by bjoliveau** [comment]
Many thanks for your feedback @glutamate
