### ISSUE TITLE
Issue : Discover Tables doesn't support frequently used PostgreSQL data types

### ISSUE THREAD

**Issue by Chlipouni** [saltcorn/saltcorn#734]
Create the following table in the PostgreSQL database :
`create table test_data_types (
  col_integer integer,
  col_double_precision double precision,
  col_float float,
  col_smallint smallint,
  col_bigint bigint,
  col_numeric numeric,
  col_numeric_8_3 numeric(8,3),
  col_char char,
  col_varchar varchar,
  col_char_10 char(10),
  col_varchar_10 varchar(10),
  col_text text,
  col_date date,
  col_time time,
  col_timestamp timestamp,
  col_boolean boolean,
  constraint pk_test_data_types primary key (col_integer),
  constraint uk_test_data_types unique (col_float)
);` 

Use the "discover tables" feature in saltcorn.

Only the following columns are discovered :
- col_integer
- col_double_precision
- col_float
- col_text
- col_boolean

Most used PotgreSQL data types should be supported in the "discover tables" feature.
These new data types could be handled with the few saltcorn data types plus value constraints.

**Comment by AleksandrSokolov** [comment]
@glutamate I can take this issue to develop.

**Comment by glutamate** [comment]
agree this would be nice. this is the function you want to add to: https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-data/models/discovery.js#L36-L45

**Comment by AleksandrSokolov** [comment]
Add support for few more sql types in https://github.com/saltcorn/saltcorn/pull/747 .
Fix problem "Table not found" for discovered tables.

@glutamate Sorry but currently I cannot add support for time, timestamp because I need your help to understand corrrect way to add this.

@glutamate Also needs help - how to deal with length of columns, precision and scale for float like types (double precision, numeric, float).

@glutamate in ideal primary key column needs to be first in column list of discovered table. Also needs some work.

@glutamate may be we need implements more attributes for columns. Needs investigation or user feed back.

@glutamate UUID column needs to be implemented.

**Comment by AleksandrSokolov** [comment]
Fixed in https://github.com/saltcorn/saltcorn/pull/752.

If you need even more sql types please one new issue.

**Comment by AleksandrSokolov** [comment]
@Chlipouni please give feed back or close issue

**Comment by Chlipouni** [comment]
The data types in my test table are now discovered.
