### ISSUE TITLE
Feature: Protect http(s) trigger call by authorization. Move trigger call to separate file.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#787]
@glutamate I want to protect http trigger call by authorization.
Plans to add min read / min write roles to _sc_triggers table and binding program code for it.
I can do this if you agreed with this feature.

Also I plan to move trigger call to api_triggers.js to make code more clean.

**Comment by glutamate** [comment]
This is a good idea. We should use the showIf to ask for minimum role in triggerForm, like this: https://github.com/saltcorn/saltcorn/blob/master/packages/server/routes/actions.js#L198. 
`showIf: { when_trigger: "API Call"}` should work

I am doing a lot of work on events right now, I just added an event log and we should also make sure that API calls get added to the event log. The big goal is to have "event driven process automation" so instead of workflows you have event handlers that can do stuff & emit other events. I hope there will be a Blockly event handler with translation to run_js_code handler to teach people to code.

**Comment by AleksandrSokolov** [comment]
Implemented in https://github.com/saltcorn/saltcorn/pull/790
[+] add _sc_triggers.min_role and binding code
[+] protect http(s) api call by authorization
[-] I did not transfer api trigger call to a separate file from api.js. A separate discussion is required.
