### ISSUE TITLE
Table.findOne(...).getRows is not a function

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#838]
I'm trying to write an action to delete/filters rows with past dates:
```
await Table.findOne({name: 'dons'})
           .deleteRows({id: (
             await Table.findOne({name: 'dons'}).getRows())});
```
I'm getting `Table.findOne(...).getRows is not a function`:
![image](https://user-images.githubusercontent.com/65325/131558791-663a7ff6-20ce-44ed-bfa0-860ca61051da.png)
```
TypeError: Table.findOne(...).getRows is not a function
    at evalmachine.<anonymous>:3:50
    at Object.run (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/actions.js:266:20)
    at Trigger.runWithoutRow (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/trigger.js:153:14)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/scheduler.js:60:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async eachTenant (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/tenant.js:94:3)
    at async run (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/scheduler.js:45:5)
    at async runScheduler (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/scheduler.js:79:5)
```
on latest docker image:
Saltcorn version | 0.5.1
Node.js v14.17.3
PostgreSQL 13.4

Additionally, I don't get how to say getRows(row.date > Date.now())
Any idea?
Thanks

**Comment by j2l** [comment]
While trying to fix it, I'm also getting errors about common JavaScript functions like `split`
How would you check if date is past or future without splitting date format like "2021-09-01T16:00:00.000Z"?

**Comment by glutamate** [comment]
Hi, a couple of problem:

```
await (await Table.findOne({name: 'dons'}))
           .deleteRows({id: (
             await (await Table.findOne({name: 'dons'})).getRows())});
```

You need to wrap the findOne in its own await. This is no longer true in a more recent version of Saltcorn, unfortunately the darker images are behind since docker hub stopped doing automated builds. I will try to do a manual push 

also, `id: (await (await Table.findOne({name: 'dons'})).getRows())})` isn't going to work, you need to map to the ids.... I would wait until I updated documents and then try this using the new Blockly actions, you should be able to do everything or at least a skeleton which can be translated to JavaScript
 

To translate "2021-09-01T16:00:00.000Z" to a date, do `new Date("2021-09-01T16:00:00.000Z")`

**Comment by j2l** [comment]
Thank you very much @glutamate 
You're fixing things blazing fast!

Too bad docker hub stopped doing automated builds, it is essential for the moment.
I can't wait to see blockly in the docker version

new Date(), I feel ashamed I didn't think of it :smile_cat:

**Comment by gianlucafiore** [comment]
Where can I see all this documentation? I'm really very lost with this and I'm guessing things through JS blocks

**Comment by j2l** [comment]
Same for me @gianlucafiore . A lot of hit and miss for now.
Writing documentation takes a long time though.

**Comment by j2l** [comment]
Great, thank you @glutamate
